import { ArrowLeft, ArrowRight, Check, CircleAlert, Coffee, CreditCard, PackageCheck, ShieldCheck, Truck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import CartDrawer from "@/components/CartDrawer";
import MizanHeader from "@/components/MizanHeader";
import { createDemoSocietySubscription, getSocietyQuote, type DemoSocietySubscription, type SocietyCadence, type SocietyDelivery, type SocietyGrind, type SocietySelection } from "@/lib/caffioSociety";
import { coffeeProducts, formatPrice, type Lang } from "@/lib/mizanCatalog";

const copy = {
  en: {
    back: "Back to Caffio", eyebrow: "CAFFIO SOCIETY / DEMO SUBSCRIPTION", titleA: "A rhythm for", titleB: "better mornings.", intro: "Choose a coffee, cadence, grind, and delivery rhythm in a local prototype. No payment, shipping, account, or subscription is created.", steps: ["Coffee", "Rhythm", "Review", "Complete"], coffee: "Choose a starting coffee", cadence: "Choose your cadence", grind: "Choose the grind", delivery: "Choose delivery", weekly: "Weekly", biweekly: "Every two weeks", monthly: "Monthly", whole: "Whole bean", filter: "Filter grind", espresso: "Espresso grind", standard: "Standard handoff", priority: "Priority handoff", standardNote: "No simulated delivery fee", priorityNote: "Demo handling fee", review: "Your Society review", demoLine: "Demo checkout — no payment or shipment is created.", live: "Live subscription route", liveBody: "Stripe keys are not configured. This interface is ready to connect when payment settings and fulfillment rules are approved.", notConfigured: "Live checkout unavailable", complete: "Create demo membership", next: "Continue", previous: "Back", successTitle: "Your demo rhythm is ready.", successBody: "A local Caffio Society record was saved in this browser. You can reset it at any time; no billing or shipping action occurred.", reset: "Start another demo", simulated: "Simulation only", product: "Coffee", total: "Demo monthly total", shipping: "Demo delivery", payment: "Payment review", paymentMethod: "Payment method — demo display", paymentValue: "No payment method collected", paymentNote: "No card is requested, stored, tokenized, or charged in this prototype.", shippingHandoff: "Shipping handoff — demo display", shippingValue: "No shipping address collected", shippingNote: "Your handoff choice changes only the demo total; no courier booking or shipment is created.", success: "Demo record created", account: "No account needed", security: "No card or address fields are collected", join: "Join Caffio Society",
  },
  ar: {
    back: "العودة إلى كافيو", eyebrow: "مجتمع كافيو / اشتراك تجريبي", titleA: "إيقاع", titleB: "لصباح أفضل.", intro: "اختر القهوة ودورة التوصيل والطحن وطريقة التسليم في نموذج محلي. لا يُنشأ اشتراك أو دفع أو شحن أو حساب فعلي.", steps: ["القهوة", "الإيقاع", "المراجعة", "الاكتمال"], coffee: "اختر قهوة البداية", cadence: "اختر دورة التوصيل", grind: "اختر الطحن", delivery: "اختر التسليم", weekly: "أسبوعيًا", biweekly: "كل أسبوعين", monthly: "شهريًا", whole: "حبوب كاملة", filter: "طحن للترشيح", espresso: "طحن للإسبريسو", standard: "تسليم اعتيادي", priority: "تسليم أولوية", standardNote: "لا رسوم تسليم تجريبية", priorityNote: "رسوم معالجة تجريبية", review: "مراجعة مجتمعك", demoLine: "إتمام تجريبي — لا يُنشأ دفع أو شحن فعلي.", live: "مسار الاشتراك الحقيقي", liveBody: "مفاتيح Stripe غير مهيأة. الواجهة جاهزة للربط عند اعتماد إعدادات الدفع وقواعد التنفيذ.", notConfigured: "الإتمام الحقيقي غير متاح", complete: "إنشاء عضوية تجريبية", next: "متابعة", previous: "رجوع", successTitle: "إيقاعك التجريبي جاهز.", successBody: "حُفظ سجل مجتمع كافيو محليًا في هذا المتصفح. يمكنك إعادة ضبطه في أي وقت؛ لم يحدث أي خصم أو شحن.", reset: "ابدأ نموذجًا آخر", simulated: "محاكاة فقط", product: "القهوة", total: "الإجمالي الشهري التجريبي", shipping: "التسليم التجريبي", payment: "مراجعة الدفع", paymentMethod: "طريقة الدفع — عرض تجريبي", paymentValue: "لا تُجمع أي طريقة دفع", paymentNote: "لا يُطلب أي رقم بطاقة أو يُخزَّن أو يُرمَّز أو يُخصم ضمن هذا النموذج.", shippingHandoff: "تسليم الشحنة — عرض تجريبي", shippingValue: "لا يُجمع عنوان شحن", shippingNote: "اختيار التسليم يغيّر الإجمالي التجريبي فقط؛ لا يُحجز مندوب أو تُنشأ شحنة.", success: "تم إنشاء السجل التجريبي", account: "لا حاجة إلى حساب", security: "لا تُجمع بيانات بطاقة أو عنوان", join: "انضم إلى مجتمع كافيو",
  },
};

const initialSelection: SocietySelection = { productId: "alto", cadence: "monthly", grind: "whole", delivery: "standard" };

function ChoiceCard<T extends string>({ active, icon, label, detail, onClick, value }: { active: boolean; icon?: React.ReactNode; label: string; detail: string; onClick: (value: T) => void; value: T }) {
  return <button type="button" className={active ? "society-choice is-selected" : "society-choice"} onClick={() => onClick(value)} aria-pressed={active}><span>{icon}</span><strong>{label}</strong><small>{detail}</small>{active && <Check size={15} />}</button>;
}

export default function CaffioSociety() {
  const [lang, setLang] = useState<Lang>(() => (localStorage.getItem("mizan-lang") as Lang) || "en");
  const [step, setStep] = useState(0);
  const [selection, setSelection] = useState<SocietySelection>(initialSelection);
  const [subscription, setSubscription] = useState<DemoSocietySubscription | null>(() => {
    try { const stored = localStorage.getItem("caffio-society-demo"); return stored ? JSON.parse(stored) : null; } catch { return null; }
  });
  const t = copy[lang];
  const quote = useMemo(() => getSocietyQuote(selection), [selection]);
  const direction = lang === "ar" ? "rtl" : "ltr";

  useEffect(() => { document.documentElement.lang = lang; document.documentElement.dir = direction; localStorage.setItem("mizan-lang", lang); }, [direction, lang]);

  const choose = <T extends keyof SocietySelection>(key: T, value: SocietySelection[T]) => setSelection((current) => ({ ...current, [key]: value }));
  const createDemo = () => { const next = createDemoSocietySubscription(selection); localStorage.setItem("caffio-society-demo", JSON.stringify(next)); setSubscription(next); setStep(3); };
  const reset = () => { localStorage.removeItem("caffio-society-demo"); setSubscription(null); setSelection(initialSelection); setStep(0); };

  return <div className="mizan-site society-site" dir={direction}>
    <MizanHeader lang={lang} onLangChange={setLang} home={false} />
    <CartDrawer lang={lang} />
    <main className="society-main">
      <div className="detail-topbar"><Link href="/"><ArrowLeft size={15} /> {t.back}</Link><span>{t.simulated}</span></div>
      <section className="society-hero"><div className="utility-chapter"><span>08</span><i /><span>08</span></div><div><p className="eyebrow"><span className="eyebrow-dot" /> {t.eyebrow}</p><h1>{t.titleA}<br /><em>{t.titleB}</em></h1><p>{t.intro}</p></div><div className="utility-seal"><span className="mizan-symbol large" aria-hidden="true"><i /><b /><em /></span><span>CAFFIO<br />SOCIETY</span></div></section>
      <section className="society-workspace"><div className="society-steps" aria-label="Subscription steps">{t.steps.map((label, index) => <span className={index === step ? "is-active" : index < step ? "is-complete" : ""} key={label}><b>{index + 1}</b><em>{label}</em></span>)}</div>
        {step < 3 ? <div className="society-flow"><div className="society-form"><div className="society-form-head"><span>0{step + 1} / 03</span><h2>{step === 0 ? t.coffee : step === 1 ? t.cadence : t.review}</h2></div>
          {step === 0 && <div className="society-product-options">{coffeeProducts.map((product) => <ChoiceCard key={product.id} value={product.id} active={selection.productId === product.id} onClick={(value) => choose("productId", value)} icon={<img src={product.image} alt="" />} label={product.shortName[lang]} detail={`${product.profile[lang]} · ${formatPrice(product.price, lang)}`} />)}</div>}
          {step === 1 && <div className="society-option-groups"><div><h3>{t.cadence}</h3><div className="society-choice-grid">{(["weekly", "biweekly", "monthly"] as SocietyCadence[]).map((value) => <ChoiceCard key={value} value={value} active={selection.cadence === value} onClick={(choice) => choose("cadence", choice)} label={t[value]} detail={value === "weekly" ? "4× / month" : value === "biweekly" ? "2× / month" : "1× / month"} />)}</div></div><div><h3>{t.grind}</h3><div className="society-choice-grid">{(["whole", "filter", "espresso"] as SocietyGrind[]).map((value) => <ChoiceCard key={value} value={value} active={selection.grind === value} onClick={(choice) => choose("grind", choice)} label={t[value]} detail={value === "whole" ? "Unspecified at checkout" : value === "filter" ? "Brew-ready simulation" : "Dial-in simulation"} />)}</div></div><div><h3>{t.delivery}</h3><div className="society-choice-grid">{(["standard", "priority"] as SocietyDelivery[]).map((value) => <ChoiceCard key={value} value={value} active={selection.delivery === value} onClick={(choice) => choose("delivery", choice)} icon={<Truck size={16} />} label={t[value]} detail={value === "standard" ? t.standardNote : t.priorityNote} />)}</div></div></div>}
          {step === 2 && <div className="society-review"><div><span>{t.product}</span><strong>{quote.product.shortName[lang]} / {selection.grind === "whole" ? t.whole : selection.grind === "filter" ? t.filter : t.espresso}</strong></div><div><span>{t.cadence}</span><strong>{t[selection.cadence]}</strong></div><div><span>{t.shipping}</span><strong>{selection.delivery === "standard" ? t.standard : t.priority}</strong></div><div className="society-review-total"><span>{t.total}</span><strong>{formatPrice(quote.total, lang)}</strong></div><div className="society-demo-review" data-testid="society-payment-shipping-demo"><div className="society-demo-surface"><CreditCard size={18} /><span><b>{t.paymentMethod}</b><strong>{t.paymentValue}</strong><small>{t.paymentNote}</small></span></div><div className="society-demo-surface"><Truck size={18} /><span><b>{t.shippingHandoff}</b><strong>{t.shippingValue}</strong><small>{t.shippingNote}</small></span></div></div><p><CircleAlert size={15} /> {t.demoLine}</p></div>}
          <div className="society-form-actions">{step > 0 && <button className="text-link" onClick={() => setStep((current) => current - 1)}><ArrowLeft size={15} /> {t.previous}</button>}{step < 2 ? <button className="button button-gold" onClick={() => setStep((current) => current + 1)}>{t.next}<ArrowRight size={15} /></button> : <button className="button button-gold" onClick={createDemo}><Check size={15} /> {t.complete}</button>}</div>
        </div><aside className="society-summary"><p className="eyebrow"><span className="eyebrow-dot" /> {t.join}</p><img src={quote.product.image} alt={`${quote.product.shortName[lang]} coffee`} /><h3>{quote.product.name[lang]}</h3><span>{quote.product.profile[lang]}</span><div><p>{t.total}<strong>{formatPrice(quote.total, lang)}</strong></p><p>{t.shipping}<strong>{formatPrice(quote.deliveryTotal, lang)}</strong></p></div><small>{t.demoLine}</small></aside></div> : <section className="society-success"><div className="success-icon"><PackageCheck size={29} /></div><p className="eyebrow"><span className="eyebrow-dot" /> {t.success}</p><h2>{t.successTitle}</h2><p>{t.successBody}</p>{subscription && <div className="society-record"><span>{subscription.id}</span><strong>{formatPrice(subscription.total, lang)}</strong><small>{new Date(subscription.createdAt).toLocaleString(lang === "ar" ? "ar-SA" : "en-US", { dateStyle: "medium" })}</small></div>}<button className="button button-gold" onClick={reset}>{t.reset}<ArrowRight size={15} /></button></section>}
        <section className="society-live-notice"><div><ShieldCheck size={20} /><span><strong>{t.live}</strong><small>{t.liveBody}</small></span></div><button type="button" disabled title={t.liveBody}><CreditCard size={15} /> {t.notConfigured}</button><p><Coffee size={15} /> {t.account} · {t.security}</p></section>
      </section>
    </main><footer className="mizan-footer"><span>CAFFIO COFFEE / SOCIETY</span><span>{t.simulated}</span><span>© 2026 / LOCAL PROTOTYPE</span></footer>
  </div>;
}
