import { ArrowLeft, ArrowUpRight, Check, Code2, Compass, Droplets, Layers3, Palette, Sparkles, Wand2 } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import CartDrawer from "@/components/CartDrawer";
import MizanHeader from "@/components/MizanHeader";
import PageMeta from "@/components/PageMeta";
import { type Lang } from "@/lib/mizanCatalog";

const copy = {
  en: {
    back: "Back to Caffio", eyebrow: "Case study / Caffio 2026", titleA: "Crafted like coffee.", titleB: "Structured like architecture.", intro: "A Neo-Minimalism 2026 concept for a luxury specialty-coffee brand: quiet enough to trust, precise enough to use.", strategy: "01 / Identity strategy", strategyTitle: "Warm minimalism with a pulse.", strategyBody: "Caffio connects the daily coffee ritual with architectural calm. The system uses restraint as a quality signal: fewer elements, stronger hierarchy, and every factual product field visibly separated from what is still awaiting a source record.", palette: "The palette", typography: "Typography system", ux: "02 / High-end UX flow", uxTitle: "A landing page that behaves like a guided tasting.", hero: "Interactive hero", heroBody: "A cinematic opening frames Caffio as a morning habit, not a commodity. The hook is direct: make the first cup feel like a room you want to return to.", showcase: "Liquid product showcase", showcaseBody: "Product cards use soft glass surfaces, roast-toned accents, and a compact origin grid to keep tasting, process, and altitude available without crowding the image.", motion: "Purposeful motion", motionBody: "Micro-interactions stay under 300ms: hover lift, brass focus states, and scroll reveals that use opacity and transform only. Reduced-motion users receive the same content without delay.", society: "03 / Caffio Society", societyTitle: "A membership ritual, not a maze.", societyBody: "The subscription engine is presented as three quick decisions. This is a front-end concept only; no payment, shipping, account, or CRM action is connected.", coffee: "Coffee", rhythm: "Rhythm", grind: "Grind", choose: "Choose a starting point", next: "Next step", seo: "04 / Search language", seoTitle: "Search should sound like the brand.", seoBody: "These are candidate semantic terms for content planning, not verified search-volume claims. Validate them against first-party data in the target market.", prompts: "05 / Visual production prompts", promptsTitle: "A small prompt atelier.", promptsBody: "Three production-ready prompts keep the image system coherent across packaging, macro detail, and lifestyle storytelling.", code: "06 / Interaction specimen", codeTitle: "A button that feels like a brass stamp.", codeLabel: "Tailwind / JSX concept", source: "Sources and handoff", sourceBody: "Open Graph and meta-description behavior follow the official protocol and Google Search Central guidance recorded in the project research notes.", openSources: "Open source notes" },
  ar: {
    back: "العودة إلى كافيو", eyebrow: "دراسة حالة / كافيو 2026", titleA: "حرفة مثل القهوة.", titleB: "وبنية مثل العمارة.", intro: "مفهوم Neo-Minimalism 2026 لعلامة قهوة مختصة فاخرة: هادئ بما يكفي للثقة، ودقيق بما يكفي للاستخدام.", strategy: "01 / استراتيجية الهوية", strategyTitle: "بساطة دافئة بنبض واضح.", strategyBody: "تربط كافيو طقس القهوة اليومي بهدوء العمارة. يستخدم النظام الاختزال كإشارة جودة: عناصر أقل، تسلسل أقوى، وفصل واضح بين بيانات المنتج الموثقة والحقول التي تنتظر سجل مصدر.", palette: "لوحة الألوان", typography: "نظام الخطوط", ux: "02 / مسار UX عالي المستوى", uxTitle: "صفحة هبوط تتصرف كجلسة تذوق موجّهة.", hero: "Hero تفاعلي", heroBody: "يفتتح المشهد السينمائي كافيو كعادة صباحية لا كسلعة. الخطاف مباشر: اجعل الكوب الأول غرفة ترغب في العودة إليها.", showcase: "عرض منتجات سائل", showcaseBody: "تستخدم البطاقات أسطحًا زجاجية هادئة ولمسات مستوحاة من التحميص وشبكة منشأ صغيرة لإبقاء التذوق والمعالجة والارتفاع متاحًا دون منافسة الصورة.", motion: "حركة هادفة", motionBody: "تبقى التفاعلات الدقيقة تحت 300ms: ارتفاع البطاقة، تركيز نحاسي، وظهور عند التمرير باستخدام الشفافية والتحويل فقط. يحصل مستخدمو تقليل الحركة على المحتوى نفسه فورًا.", society: "03 / مجتمع كافيو", societyTitle: "طقس عضوية لا متاهة.", societyBody: "يُعرض محرك الاشتراك كاختيارات سريعة من ثلاث خطوات. هذا مفهوم أمامي فقط؛ لا يوجد دفع أو شحن أو حساب أو CRM متصل.", coffee: "القهوة", rhythm: "الإيقاع", grind: "الطحن", choose: "اختر نقطة البداية", next: "الخطوة التالية", seo: "04 / لغة البحث", seoTitle: "يجب أن تبدو نتائج البحث مثل العلامة.", seoBody: "هذه كلمات دلالية مرشحة لتخطيط المحتوى وليست ادعاءات بحجم بحث مثبت. يجب التحقق منها عبر بيانات المصدر الأول في السوق المستهدف.", prompts: "05 / برومبتات الإنتاج البصري", promptsTitle: "ورشة برومبت صغيرة.", promptsBody: "ثلاثة برومبتات جاهزة للإنتاج تحافظ على اتساق الصورة بين التغليف والتفاصيل الماكرو وقصة أسلوب الحياة.", code: "06 / نموذج تفاعلي", codeTitle: "زر يبدو كختم نحاسي.", codeLabel: "مفهوم Tailwind / JSX", source: "المصادر والتسليم", sourceBody: "تتبع علامات Open Graph ووصف الصفحات البروتوكول الرسمي وإرشادات Google Search Central المسجلة في ملاحظات البحث بالمشروع.", openSources: "فتح ملاحظات المصادر" },
};

const palette = [
  { name: "Organic Ivory", hex: "#F2EBDD", note: "السطح العضوي / القراءة الهادئة" },
  { name: "Roast Charcoal", hex: "#182022", note: "الثقة / العمق / التركيز" },
  { name: "Caffio Brass", hex: "#B89152", note: "الإشارة / الحرفة / الفعل" },
  { name: "First Crack", hex: "#8C5A3C", note: "درجة التحميص / الدفء" },
];

const keywords = ["القهوة المختصة", "specialty coffee", "قهوة محمصة طازجة", "single origin coffee", "قهوة مستدامة", "home coffee brewing", "أدوات التحضير المنزلية", "coffee tasting notes", "light roast coffee", "coffee subscription" ];
const prompts = [
  "Caffio coffee packaging on a quiet modern kitchen island, warm ivory stone, architectural shadows, roast-brown paper, aged brass foil mark, cinematic morning light, 50mm editorial product photography, restrained Neo-Minimalism, no legible placeholder text, no logos except the supplied Caffio mark.",
  "Macro studio photograph of freshly roasted coffee beans with a thin veil of coffee steam, tactile surface detail, warm charcoal background, brass rim light, high-end specialty coffee campaign, shallow depth of field, controlled highlights, no text, no watermark.",
  "Art-directed lifestyle scene: a human hand placing a Caffio coffee cup beside a notebook in a quiet morning room, soft window light, organic ivory and charcoal palette, architectural composition, intimate but not staged, premium editorial photography, no text, no watermark.",
];

export default function CaseStudy() {
  const [lang, setLang] = useState<Lang>(() => (localStorage.getItem("mizan-lang") as Lang) || "en");
  const [step, setStep] = useState(0);
  const t = copy[lang];
  const societySteps = [t.coffee, t.rhythm, t.grind];
  const code = `<button className="group rounded-full bg-[#B89152] px-6 py-3 text-[#182022] transition duration-200 hover:-translate-y-1 hover:bg-[#D3AE6B] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4">\n  {label} <ArrowUpRight className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" />\n</button>`;

  return <div className="mizan-site case-site" dir={lang === "ar" ? "rtl" : "ltr"}>
    <PageMeta lang={lang} />
    <MizanHeader lang={lang} onLangChange={setLang} home={false} />
    <CartDrawer lang={lang} />
    <main>
      <div className="detail-topbar case-topbar"><Link href="/"><ArrowLeft size={15} /> {t.back}</Link><span>{t.eyebrow}</span></div>
      <section className="case-hero"><div className="utility-chapter"><span>CS</span><i /><span>06</span></div><div><p className="eyebrow"><span className="eyebrow-dot" /> {t.eyebrow}</p><h1>{t.titleA}<br /><em>{t.titleB}</em></h1><p>{t.intro}</p></div><div className="utility-seal"><span className="mizan-symbol large" aria-hidden="true"><i /><b /><em /></span><span>CAFFIO<br />2026</span></div></section>
      <section className="case-section case-strategy"><div className="case-section-label"><span>{t.strategy}</span><Palette size={18} /></div><div className="case-split"><div><h2>{t.strategyTitle}</h2><p>{t.strategyBody}</p></div><div className="case-palette"><p className="eyebrow"><span className="eyebrow-dot" /> {t.palette}</p>{palette.map((item) => <div className="palette-row" key={item.hex}><span className="palette-swatch" style={{ background: item.hex }} /><span><strong>{item.name}</strong><small>{item.hex} · {item.note}</small></span></div>)}</div></div><div className="case-type-strip"><div><p className="eyebrow">DISPLAY / 400–500</p><strong className="case-display">DM Serif Display</strong><span>Large editorial statements, chapter titles, and sensory contrast.</span></div><div><p className="eyebrow">FUNCTION / 400–700</p><strong>Manrope</strong><span>Arabic and English interface copy, metadata, labels, and controls.</span></div></div></section>
      <section className="case-section case-ux"><div className="case-section-label"><span>{t.ux}</span><Compass size={18} /></div><h2>{t.uxTitle}</h2><div className="case-ux-grid"><article><span className="case-number">01</span><Sparkles size={19} /><h3>{t.hero}</h3><p>{t.heroBody}</p></article><article><span className="case-number">02</span><Droplets size={19} /><h3>{t.showcase}</h3><p>{t.showcaseBody}</p></article><article><span className="case-number">03</span><Wand2 size={19} /><h3>{t.motion}</h3><p>{t.motionBody}</p></article></div></section>
      <section className="case-section case-society"><div className="case-section-label"><span>{t.society}</span><Layers3 size={18} /></div><div className="case-society-layout"><div><h2>{t.societyTitle}</h2><p>{t.societyBody}</p></div><div className="society-demo"><div className="society-progress"><span style={{ width: `${(step + 1) * 33.33}%` }} /></div><div className="society-step-label">0{step + 1} / 03</div><h3>{t.choose}</h3><div className="society-options">{societySteps.map((item, index) => <button key={item} className={step === index ? "is-active" : ""} onClick={() => setStep(index)} aria-pressed={step === index}>{step === index && <Check size={14} />}{item}</button>)}</div><button className="button button-gold" onClick={() => setStep((step + 1) % 3)}>{t.next}<ArrowUpRight size={14} /></button></div></div></section>
      <section className="case-section case-seo"><div className="case-section-label"><span>{t.seo}</span><Code2 size={18} /></div><div className="case-split"><div><h2>{t.seoTitle}</h2><p>{t.seoBody}</p><div className="keyword-cloud">{keywords.map((keyword) => <span key={keyword}>{keyword}</span>)}</div></div><div className="meta-card"><p className="eyebrow">META DESCRIPTION / EN</p><strong>Discover Caffio specialty coffee, origin-led tasting notes, and thoughtful home brewing rituals for mornings with more clarity.</strong><p className="eyebrow">META DESCRIPTION / AR</p><strong dir="rtl">اكتشف قهوة كافيو المختصة، وإيحاءات المنشأ، وطقوس التحضير المنزلي لصباح أكثر صفاءً.</strong></div></div></section>
      <section className="case-section case-prompts"><div className="case-section-label"><span>{t.prompts}</span><Wand2 size={18} /></div><h2>{t.promptsTitle}</h2><p className="case-lead">{t.promptsBody}</p><div className="prompt-list">{prompts.map((prompt, index) => <details key={prompt} open={index === 0}><summary><span>0{index + 1}</span>{["Packaging / Modern kitchen", "Macro / Studio steam", "Lifestyle / Morning ritual"][index]}</summary><p>{prompt}</p></details>)}</div></section>
      <section className="case-section case-code"><div className="case-section-label"><span>{t.code}</span><Code2 size={18} /></div><div className="case-split"><div><h2>{t.codeTitle}</h2><p>{t.codeLabel}</p></div><pre><code>{code}</code></pre></div></section>
      <section className="case-handoff"><p className="eyebrow"><span className="eyebrow-dot" /> {t.source}</p><p>{t.sourceBody}</p><Link className="text-link" href="/">{t.openSources}<ArrowUpRight size={15} /></Link></section>
    </main>
    <footer className="mizan-footer"><span>CAFFIO COFFEE / SPECIALTY ROASTERS</span><span>{lang === "ar" ? "طقس مصمم بعناية" : "A RITUAL, DESIGNED"}</span><span>© 2026 / CASE STUDY</span></footer>
  </div>;
}
