import { ArrowLeft, ArrowUpRight, ChevronDown, Clock3, Filter, Search, SlidersHorizontal, X } from "lucide-react";
import { useEffect, useLayoutEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import CartDrawer from "@/components/CartDrawer";
import MizanHeader from "@/components/MizanHeader";
import ResponsiveImage from "@/components/ResponsiveImage";
import { coffeeProducts, formatPrice, type Lang } from "@/lib/mizanCatalog";
import { documentedTastingNotes, relatedProducts } from "@/lib/productDiscovery";
import { responsiveImages } from "@/lib/responsiveImages";

type Sort = "featured" | "price-asc" | "price-desc" | "name";
type RecentSearch = { term: string; at: number };
type SavedFilters = { roast: string; brew: string; tasting: string; price: string; sort: Sort };
const RECENT_SEARCH_KEY = "caffio-recent-product-searches-v1";
const FILTER_MEMORY_KEY = "caffio-product-search-filters-v1";

const copy = {
  en: { back: "Back to Caffio", eyebrow: "CAFFIO / PRODUCT SEARCH", titleA: "Find your", titleB: "starting point.", intro: "Search the working collection, then refine it by roast, brew method, and demo price. Product facts remain marked as pending until source records are attached.", search: "Search coffee, profile, or brew method", filters: "Refine results", filtersSaved: "Filters saved on this browser", roast: "Roast", brew: "Brew method", tasting: "Tasting note", tastingAll: "All documented notes", tastingUnavailable: "Tasting-note filters unlock only after a verified batch record is attached.", price: "Demo price", allRoasts: "All roasts", allBrews: "All brew methods", anyPrice: "Any price", under18: "Under $18", from18to19: "$18–$19", from20: "$20 and above", sort: "Sort by", featured: "Editorial order", priceAsc: "Price: low to high", priceDesc: "Price: high to low", name: "Name", results: "coffees found", clear: "Clear filters", noTitle: "No coffees match this view.", noBody: "Try clearing a filter or search with a broader word. The current catalog is intentionally small while source records are prepared.", reset: "Reset search", details: "View details", sourcePending: "Source record pending", demo: "Demo price", related: "Related starting points", relatedBody: "Selected from roast, shared brew methods, and any shared notes from verified batch records only.", relatedEmpty: "No related catalog match is documented for this view yet.", recent: "Recent searches", recentBody: "Saved in this browser only. No account or profile is created.", clearRecent: "Clear recent searches" },
  ar: { back: "العودة إلى كافيو", eyebrow: "كافيو / بحث المنتجات", titleA: "اعثر على", titleB: "نقطة بدايتك.", intro: "ابحث في المجموعة الحالية ثم صفِّ النتائج بالتحميص وطريقة التحضير والسعر التجريبي. تبقى حقائق المنتج موسومة بأنها قيد التوثيق إلى أن تُرفق سجلات المصدر.", search: "ابحث عن قهوة أو ملف أو طريقة تحضير", filters: "صقل النتائج", filtersSaved: "الفلاتر محفوظة في هذا المتصفح", roast: "التحميص", brew: "طريقة التحضير", tasting: "إيحاءات التذوق", tastingAll: "كل الإيحاءات الموثقة", tastingUnavailable: "تتوافر تصفية الإيحاءات بعد إرفاق سجل دفعة موثّق فقط.", price: "السعر التجريبي", allRoasts: "كل التحميصات", allBrews: "كل طرق التحضير", anyPrice: "أي سعر", under18: "أقل من 18 دولارًا", from18to19: "18–19 دولارًا", from20: "20 دولارًا فأعلى", sort: "ترتيب حسب", featured: "الترتيب التحريري", priceAsc: "السعر: الأقل أولًا", priceDesc: "السعر: الأعلى أولًا", name: "الاسم", results: "قهوة متاحة", clear: "مسح التصفية", noTitle: "لا توجد قهوة مطابقة لهذا العرض.", noBody: "جرّب مسح فلتر أو كلمة بحث أوسع. الكتالوج صغير عمدًا بينما تُجهّز سجلات المصدر.", reset: "إعادة ضبط البحث", details: "عرض التفاصيل", sourcePending: "سجل المصدر قيد الإعداد", demo: "سعر تجريبي", related: "نقاط بداية مرتبطة", relatedBody: "مختارة من التحميص وطرق التحضير المشتركة وأي إيحاءات مشتركة في سجلات دفعات موثقة فقط.", relatedEmpty: "لا توجد علاقة موثقة بمنتجات أخرى لهذا العرض حتى الآن.", recent: "عمليات البحث الأخيرة", recentBody: "محفوظة في هذا المتصفح فقط. لا يُنشأ حساب أو ملف شخصي.", clearRecent: "مسح عمليات البحث" },
};

function initialParam(key: string, fallback = "all") { return new URLSearchParams(window.location.search).get(key) || fallback; }
function loadRecentSearches(): RecentSearch[] { try { const value = JSON.parse(localStorage.getItem(RECENT_SEARCH_KEY) || "[]"); return Array.isArray(value) ? value.filter((item): item is RecentSearch => typeof item?.term === "string" && typeof item?.at === "number").slice(0, 5) : []; } catch { return []; } }
function loadSavedFilters(): SavedFilters { try { const value = JSON.parse(localStorage.getItem(FILTER_MEMORY_KEY) || "{}"); return { roast: typeof value.roast === "string" ? value.roast : "all", brew: typeof value.brew === "string" ? value.brew : "all", tasting: typeof value.tasting === "string" ? value.tasting : "all", price: typeof value.price === "string" ? value.price : "all", sort: ["featured", "price-asc", "price-desc", "name"].includes(value.sort) ? value.sort : "featured" }; } catch { return { roast: "all", brew: "all", tasting: "all", price: "all", sort: "featured" }; } }

export default function ProductSearch() {
  const [lang, setLang] = useState<Lang>(() => (localStorage.getItem("mizan-lang") as Lang) || "en");
  const [query, setQuery] = useState(() => initialParam("q", ""));
  const [roast, setRoast] = useState(() => initialParam("roast", loadSavedFilters().roast));
  const [brew, setBrew] = useState(() => initialParam("brew", loadSavedFilters().brew));
  const [tasting, setTasting] = useState(() => initialParam("tasting", loadSavedFilters().tasting));
  const [price, setPrice] = useState(() => initialParam("price", loadSavedFilters().price));
  const [sort, setSort] = useState<Sort>(() => initialParam("sort", loadSavedFilters().sort) as Sort);
  const [recentSearches, setRecentSearches] = useState<RecentSearch[]>(loadRecentSearches);
  const [isUpdating, setIsUpdating] = useState(false);
  const [filtersReady, setFiltersReady] = useState(false);
  const [shouldPersistFilters, setShouldPersistFilters] = useState(true);
  const t = copy[lang];
  const direction = lang === "ar" ? "rtl" : "ltr";
  const brewOptions = useMemo(() => Array.from(new Set(coffeeProducts.flatMap((product) => product.brewMethods.map((method) => method[lang])))), [lang]);
  const tastingOptions = useMemo(() => Array.from(new Set(coffeeProducts.flatMap((product) => documentedTastingNotes(product, lang)))), [lang]);
  const startUpdate = () => setIsUpdating(true);

  useEffect(() => { const params = new URLSearchParams(window.location.search); if (!params.has("roast") && !params.has("brew") && !params.has("tasting") && !params.has("price") && !params.has("sort")) { const saved = loadSavedFilters(); setRoast(saved.roast); setBrew(saved.brew); setTasting(saved.tasting); setPrice(saved.price); setSort(saved.sort); } setFiltersReady(true); }, []);
  useEffect(() => { const params = new URLSearchParams(); if (query.trim()) params.set("q", query.trim()); if (roast !== "all") params.set("roast", roast); if (brew !== "all") params.set("brew", brew); if (tasting !== "all") params.set("tasting", tasting); if (price !== "all") params.set("price", price); if (sort !== "featured") params.set("sort", sort); window.history.replaceState({}, "", `${window.location.pathname}${params.size ? `?${params}` : ""}`); }, [query, roast, brew, tasting, price, sort]);
  useLayoutEffect(() => { if (filtersReady && shouldPersistFilters) localStorage.setItem(FILTER_MEMORY_KEY, JSON.stringify({ roast, brew, tasting, price, sort })); }, [filtersReady, roast, brew, tasting, price, shouldPersistFilters, sort]);
  useEffect(() => { if (!query.trim()) return; const timer = window.setTimeout(() => { const term = query.trim(); setRecentSearches((current) => { const next = [{ term, at: Date.now() }, ...current.filter((item) => item.term.toLocaleLowerCase() !== term.toLocaleLowerCase())].slice(0, 5); localStorage.setItem(RECENT_SEARCH_KEY, JSON.stringify(next)); return next; }); }, 600); return () => window.clearTimeout(timer); }, [query]);
  useEffect(() => { if (!isUpdating) return; const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches; const timer = window.setTimeout(() => setIsUpdating(false), reduced ? 0 : 180); return () => window.clearTimeout(timer); }, [isUpdating, query, roast, brew, tasting, price, sort]);

  const results = useMemo(() => coffeeProducts.filter((product) => {
    const haystack = [product.name[lang], product.shortName[lang], product.profile[lang], product.origin[lang], product.process[lang], ...product.brewMethods.map((method) => method[lang])].join(" ").toLocaleLowerCase(lang === "ar" ? "ar" : "en");
    return (!query.trim() || haystack.includes(query.trim().toLocaleLowerCase(lang === "ar" ? "ar" : "en"))) && (roast === "all" || product.roastTone === roast) && (brew === "all" || product.brewMethods.some((method) => method[lang] === brew)) && (tasting === "all" || documentedTastingNotes(product, lang).includes(tasting)) && (price === "all" || (price === "under18" && product.price < 18) || (price === "18to19" && product.price >= 18 && product.price < 20) || (price === "from20" && product.price >= 20));
  }).sort((a, b) => sort === "price-asc" ? a.price - b.price : sort === "price-desc" ? b.price - a.price : sort === "name" ? a.name[lang].localeCompare(b.name[lang], lang) : coffeeProducts.indexOf(a) - coffeeProducts.indexOf(b)), [brew, lang, price, query, roast, sort, tasting]);
  const related = relatedProducts(results[0], coffeeProducts, 2);
  const reset = () => { startUpdate(); setQuery(""); setRoast("all"); setBrew("all"); setTasting("all"); setPrice("all"); setSort("featured"); };
  const clearRecent = () => { localStorage.removeItem(RECENT_SEARCH_KEY); setRecentSearches([]); };
  const clearSavedFilterPreferences = () => { setShouldPersistFilters(false); localStorage.removeItem(FILTER_MEMORY_KEY); startUpdate(); setRoast("all"); setBrew("all"); setTasting("all"); setPrice("all"); setSort("featured"); };

  return <div className="mizan-site search-site" dir={direction}>
    <MizanHeader lang={lang} onLangChange={setLang} home={false} /><CartDrawer lang={lang} />
    <main className="product-search-main">
      <div className="detail-topbar"><Link href="/"><ArrowLeft size={15} /> {t.back}</Link><span>{results.length} {t.results}</span></div>
      <button className="clear-saved-filters" data-testid="clear-saved-filter-preferences" type="button" onClick={clearSavedFilterPreferences}>{lang === "ar" ? "مسح تفضيلات الفلاتر المحفوظة" : "Clear saved filter preferences"}</button>
      <section className="search-hero"><p className="eyebrow"><span className="eyebrow-dot" /> {t.eyebrow}</p><h1>{t.titleA}<br /><em>{t.titleB}</em></h1><p>{t.intro}</p><label className="product-search-input"><Search size={20} /><input value={query} onChange={(event) => { startUpdate(); setQuery(event.target.value); }} placeholder={t.search} aria-label={t.search} /><span>{query && <button type="button" onClick={() => { startUpdate(); setQuery(""); }} aria-label={t.clear}><X size={16} /></button>}</span></label>{recentSearches.length > 0 && <div className="recent-searches" data-testid="recent-searches"><div><span><Clock3 size={14} /> {t.recent}</span><button type="button" onClick={clearRecent}>{t.clearRecent}</button></div><p>{t.recentBody}</p><ul>{recentSearches.map((item) => <li key={`${item.term}-${item.at}`}><button type="button" onClick={() => { startUpdate(); setQuery(item.term); }}>{item.term}</button></li>)}</ul></div>}</section>
      <section className="search-results-section" onChange={() => setShouldPersistFilters(true)}><aside className="search-filters" aria-label={t.filters}><div className="search-filter-head"><span><SlidersHorizontal size={16} /> {t.filters}</span><button type="button" onClick={reset}>{t.clear}</button></div><p className="filter-memory" data-testid="saved-search-filters">{t.filtersSaved}</p><label><span>{t.roast}</span><select value={roast} onChange={(event) => { startUpdate(); setRoast(event.target.value); }}><option value="all">{t.allRoasts}</option><option value="light">{lang === "ar" ? "خفيف" : "Light"}</option><option value="medium">{lang === "ar" ? "متوسط" : "Medium"}</option><option value="espresso">{lang === "ar" ? "إسبريسو" : "Espresso"}</option></select></label><label><span>{t.brew}</span><select value={brew} onChange={(event) => { startUpdate(); setBrew(event.target.value); }}><option value="all">{t.allBrews}</option>{brewOptions.map((option) => <option key={option} value={option}>{option}</option>)}</select></label><label><span>{t.tasting}</span><select value={tasting} disabled={!tastingOptions.length} aria-describedby="tasting-note-filter-status" onChange={(event) => { startUpdate(); setTasting(event.target.value); }}><option value="all">{t.tastingAll}</option>{tastingOptions.map((option) => <option key={option} value={option}>{option}</option>)}</select><small id="tasting-note-filter-status">{tastingOptions.length ? "" : t.tastingUnavailable}</small></label><label><span>{t.price}</span><select value={price} onChange={(event) => { startUpdate(); setPrice(event.target.value); }}><option value="all">{t.anyPrice}</option><option value="under18">{t.under18}</option><option value="18to19">{t.from18to19}</option><option value="from20">{t.from20}</option></select></label></aside>
        <div className="search-results"><div className="search-results-head"><p><Filter size={15} /> {results.length} {t.results}</p><label><span>{t.sort}</span><select value={sort} onChange={(event) => { startUpdate(); setSort(event.target.value as Sort); }}><option value="featured">{t.featured}</option><option value="price-asc">{t.priceAsc}</option><option value="price-desc">{t.priceDesc}</option><option value="name">{t.name}</option></select><ChevronDown size={14} /></label></div><div className={isUpdating ? "search-results-body is-updating" : "search-results-body"} aria-busy={isUpdating}>{isUpdating && <div className="search-skeleton-grid" aria-hidden="true">{Array.from({ length: 3 }).map((_, index) => <div className="search-skeleton-card" key={index}><i /><span><b /><b /><b /></span></div>)}</div>}{results.length ? <div className="search-product-grid">{results.map((product) => <article className="search-product-card" key={product.id}><ResponsiveImage image={responsiveImages[product.imageKey]} alt={`${product.shortName[lang]} coffee`} loading="lazy" decoding="async" /><div><span>{t.sourcePending}</span><h2>{product.name[lang]}</h2><p>{product.profile[lang]}</p><small>{product.brewMethods.map((method) => method[lang]).join(" · ")}</small><div><strong>{t.demo} / {formatPrice(product.price, lang)}</strong><Link className="text-link" href={`/coffee/${product.id}`}>{t.details}<ArrowUpRight size={14} /></Link></div></div></article>)}</div> : <div className="search-empty" role="status"><Search size={28} /><h2>{t.noTitle}</h2><p>{t.noBody}</p><button className="button button-gold" type="button" onClick={reset}>{t.reset}<ArrowUpRight size={15} /></button></div>}</div>
          {results.length > 0 && <section className="search-related" data-testid="related-products"><p className="eyebrow"><span className="eyebrow-dot" /> {t.related}</p><p>{t.relatedBody}</p>{related.length ? <div>{related.map((product) => <Link key={product.id} href={`/coffee/${product.id}`}><span>{product.shortName[lang]}</span><strong>{product.profile[lang]}</strong><ArrowUpRight size={14} /></Link>)}</div> : <p className="search-related-empty" role="status">{t.relatedEmpty}</p>}</section>}
        </div>
      </section>
    </main>
    <footer className="mizan-footer"><span>CAFFIO COFFEE / SPECIALTY ROASTERS</span><span>{lang === "ar" ? "بحث منظم" : "A CONSIDERED SEARCH"}</span><span>© 2026 / PRODUCT SEARCH</span></footer>
  </div>;
}
