import { ArrowLeft, ArrowUpRight, Clock3, Heart, PackageCheck, Trash2, UserRound } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import MizanHeader from "@/components/MizanHeader";
import CartDrawer from "@/components/CartDrawer";
import { getCartProducts, useCart, type DemoOrder } from "@/contexts/CartContext";
import { useFavorites } from "@/contexts/FavoritesContext";
import { coffeeProducts, formatPrice, type Lang } from "@/lib/mizanCatalog";

const copy = {
  en: { back: "Back to MIZAN", eyebrow: "MIZAN / LOCAL PROFILE", titleA: "Keep the", titleB: "ritual together.", intro: "A browser-local profile for demo orders and saved coffees. No account, email, payment, or shipping details are stored.", local: "Local only / no account", orders: "Demo order history", favorites: "Saved coffees", noOrders: "No demo orders yet.", noOrdersBody: "Complete the simulated checkout and the order will appear in this local profile.", shop: "Explore the collection", noFavorites: "No saved coffees yet.", noFavoritesBody: "Use the heart on a product detail page to keep a coffee close.", clearOrders: "Clear order history", clearFavorites: "Clear saved coffees", track: "Track order", viewCoffee: "View coffee", items: "items", empty: "No line items", status: ["Order received", "Roast scheduled", "Packed", "Ready for handoff"], order: "Demo order", created: "Created", demo: "Simulation only" },
  ar: { back: "العودة إلى ميزان", eyebrow: "ميزان / الملف المحلي", titleA: "اجمع", titleB: "الطقس في مكان واحد.", intro: "ملف محلي في المتصفح للطلبات التجريبية والقهوة المحفوظة. لا تُخزن بيانات حساب أو بريد أو دفع أو شحن.", local: "محلي فقط / بلا حساب", orders: "سجل الطلبات التجريبية", favorites: "القهوة المفضلة", noOrders: "لا توجد طلبات تجريبية بعد.", noOrdersBody: "أتمم محاكاة الطلب وستظهر النتيجة في هذا الملف المحلي.", shop: "استكشف المجموعة", noFavorites: "لا توجد قهوة محفوظة بعد.", noFavoritesBody: "استخدم القلب في صفحة تفاصيل المنتج لحفظ القهوة قريبًا.", clearOrders: "مسح سجل الطلبات", clearFavorites: "مسح القهوة المحفوظة", track: "تتبع الطلب", viewCoffee: "عرض القهوة", items: "عناصر", empty: "لا توجد عناصر", status: ["تم استلام الطلب", "جدولة التحميص", "تم التجهيز", "جاهز للتسليم"], order: "الطلب التجريبي", created: "تاريخ الإنشاء", demo: "محاكاة فقط" },
};

function OrderHistoryCard({ order, lang, statusLabels }: { order: DemoOrder; lang: Lang; statusLabels: string[] }) {
  const products = getCartProducts(order.items);
  return <article className="profile-order-card"><div className="profile-order-head"><div><span>{statusLabels[order.statusIndex]}</span><strong>{order.id}</strong></div><PackageCheck size={20} /></div><div className="profile-order-meta"><span>{new Date(order.createdAt).toLocaleString(lang === "ar" ? "ar-SA" : "en-US", { dateStyle: "medium" })}</span><strong>{formatPrice(order.total, lang)}</strong></div><div className="profile-order-items">{products.length ? products.map((product) => <Link key={product.id} href={`/coffee/${product.id}`}><img src={product.image} alt="" /><span>{product.shortName[lang]}<small>{order.items[product.id]} × {formatPrice(product.price, lang)}</small></span><ArrowUpRight size={14} /></Link>) : <span>{lang === "ar" ? "لا توجد عناصر" : "No line items"}</span>}</div><Link className="text-link" href="/track">{lang === "ar" ? "فتح التتبع" : "Open tracking"}<ArrowUpRight size={14} /></Link></article>;
}

export default function Profile() {
  const [lang, setLang] = useState<Lang>(() => (localStorage.getItem("mizan-lang") as Lang) || "en");
  const { orders, clearOrders } = useCart();
  const { favorites, clear: clearFavorites } = useFavorites();
  const t = copy[lang];
  const savedProducts = coffeeProducts.filter((product) => favorites.includes(product.id));

  return <div className="mizan-site profile-site" dir={lang === "ar" ? "rtl" : "ltr"}>
    <MizanHeader lang={lang} onLangChange={setLang} home={false} />
    <CartDrawer lang={lang} />
    <main className="profile-main"><div className="detail-topbar"><Link href="/"><ArrowLeft size={15} /> {t.back}</Link><span>{t.local}</span></div><section className="profile-hero"><div className="utility-chapter"><span>07</span><i /><span>07</span></div><div className="utility-copy"><p className="eyebrow"><span className="eyebrow-dot" /> {t.eyebrow}</p><h1>{t.titleA}<br /><em>{t.titleB}</em></h1><p>{t.intro}</p></div><div className="utility-seal"><span className="mizan-symbol large" aria-hidden="true"><i /><b /><em /></span><UserRound size={18} /><span>LOCAL<br />PROFILE</span></div></section><section className="profile-dashboard"><div className="profile-stats"><div><Clock3 size={17} /><span>{t.orders}</span><strong>{orders.length}</strong></div><div><Heart size={17} /><span>{t.favorites}</span><strong>{favorites.length}</strong></div><div><PackageCheck size={17} /><span>{t.demo}</span><strong>100%</strong></div></div><div className="profile-grid"><section className="profile-column"><div className="profile-section-head"><div><p className="eyebrow"><span className="eyebrow-dot" /> {t.orders}</p><h2>{t.orders}</h2></div>{orders.length > 0 && <button className="text-link" onClick={clearOrders}><Trash2 size={14} /> {t.clearOrders}</button>}</div>{orders.length ? <div className="profile-orders">{orders.map((order) => <OrderHistoryCard key={order.id} order={order} lang={lang} statusLabels={t.status} />)}</div> : <div className="profile-empty"><Clock3 size={23} /><h3>{t.noOrders}</h3><p>{t.noOrdersBody}</p><Link className="button button-gold" href="/#collection">{t.shop}<ArrowUpRight size={14} /></Link></div>}</section><section className="profile-column"><div className="profile-section-head"><div><p className="eyebrow"><span className="eyebrow-dot" /> {t.favorites}</p><h2>{t.favorites}</h2></div>{savedProducts.length > 0 && <button className="text-link" onClick={clearFavorites}><Trash2 size={14} /> {t.clearFavorites}</button>}</div>{savedProducts.length ? <div className="profile-favorites">{savedProducts.map((product) => <Link key={product.id} href={`/coffee/${product.id}`} className="profile-favorite"><img src={product.image} alt={`${product.shortName[lang]} coffee`} /><span><strong>{product.shortName[lang]}</strong><small>{product.profile[lang]}</small></span><ArrowUpRight size={14} /></Link>)}</div> : <div className="profile-empty"><Heart size={23} /><h3>{t.noFavorites}</h3><p>{t.noFavoritesBody}</p><Link className="text-link" href="/favorites">{t.favorites}<ArrowUpRight size={14} /></Link></div>}</section></div></section></main><footer className="mizan-footer"><span>MIZAN COFFEE / SPECIALTY ROASTERS</span><span>{lang === "ar" ? "توازن في كل كوب" : "BALANCE IN EVERY CUP"}</span><span>© 2026 / LOCAL PROFILE</span></footer>
  </div>;
}
